kind: Deployment
apiVersion: apps/v1
metadata:
  name: encrypted-svc
  labels:
    app: eva
    name: encrypted-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eva
      task: encrypted-svc
  template:
    metadata:
      labels:
        app: eva
        task: encrypted-svc
    spec:
      containers:
        - name: eva-deployment
          image: ghcr.io/panosis/heaan-svc-thesis:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-image-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: encrypted-svc
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: eva
    task: encrypted-svc
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: encrypted-svc
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: encrypted-svc
                port:
                  number: 80